version = 0.1
[default.deploy.parameters]
stack_name = "sf-app-dev"
resolve_s3 = true
s3_prefix = "sf-app-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"dev\" OpenAiModel=\"gpt-4\" TypeformFormId=\"YOUR_TYPEFORM_FORM_ID\" CognitoUserPoolId=\"YOUR_COGNITO_USER_POOL_ID\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "sf-app-prod"
resolve_s3 = true
s3_prefix = "sf-app-prod"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"prod\" OpenAiModel=\"gpt-4-0613\" TypeformFormId=\"YOUR_TYPEFORM_FORM_ID\" CognitoUserPoolId=\"YOUR_COGNITO_USER_POOL_ID\""
image_repositories = []